name: ci-dev

on:
  push:
    branches:
      - 'main'
jobs:
  docker-build-and-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: create dotenv
        run: |
          touch ./.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./.env
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_ID }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.REGISTRY_HOST }}/studium-server:latest
  # docker-pull-and-restart:
  #   environment: dev
  #   runs-on: ubuntu-latest
  #   needs: docker-build-and-push
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: create ansible secrets
  #       run: |
  #         touch ./ansible/secrets.yml
  #         echo "user: '${{ secrets.ANSIBLE_USER }}'" >> ./ansible/secrets.yml
  #         echo "registry_host: '${{ secrets.REGISTRY_HOST }}'" >> ./ansible/secrets.yml
  #         echo "registry_user: '${{ secrets.REGISTRY_ID }}'" >> ./ansible/secrets.yml
  #         echo "registry_password: '${{ secrets.REGISTRY_PASSWORD }}'" >> ./ansible/secrets.yml
  #     - name: Run Playbook
  #       uses: dawidd6/action-ansible-playbook@v2
  #       with:
  #         playbook: deploy-playbook.yml
  #         directory: ./ansible
  #         key: ${{secrets.SSH_PRIVATE_KEY}}
  #         inventory: ${{secrets.ANSIBLE_INVENTORY}}
